#!/usr/bin/env sh

#Reset rules at every reload
bspc rule -r "*"

#Heavily inspired by
#https://gitlab.com/protesilaos/dotfiles
#
_bc() {
  bspc config "$@"
}

_check() {
  command -v "$1" > /dev/null
}
#sxhkd &

#https://gitlab.com/protesilaos/dotfiles/blob/master/bspwm/.config/bspwm/bspwmrc
#Suddenly stopped to work :thinking:
#_check sxhkd && sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc{,_bspc} &
_check sxhkd && sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

#bspc monitor -d 1-web 2-shell 3-fm 4 5 6 7-test 8-crap 9-what 10-monitor

~/.config/bspwm/scripts/monitor-setup

_bc automatic_scheme			alternate

_bc pointer_modifier			shift
_bc pointer_action1			move
_bc pointer_action2			resize_side
_bc pointer_action3			resize_corner

_bc focus_follows_pointer		true
_bc click_to_focus			true
_bc history_aware_focus			true

_bc remove_disabled_monitors		true
_bc remove_unplugged_monitors		true
_bc merge_overlapping_monitors		true

#Valid inputs: \#4c566a "#4c566a"
_bc normal_border_color 		"#312e30"
_bc active_border_color 		"#b1932b"
_bc focused_border_color    		"#6da280"
_bc presel_feedback_color		"#2a2829"
_bc urgent_border_color			"#dd2727"
	
_bc top_padding 			0	
_bc bottom_padding 			0	
_bc left_padding 			0	
_bc right_padding 			0
_bc border_width        		1

_bc window_gap          		18

_bc split_ratio          		0.52
_bc center_pseudo_tiled 		false
_bc single_monocle 			true
_bc borderless_monocle  		true
_bc gapless_monocle     		true


#Autostart
killall "nm-applet"
nm-applet &
#killall "dunst"
#dunst &
#nitrogen --restore &
#polybar top &
#sh .screenlayout/default.sh &
#feh --bg-fill ~/Pictures/blur.png &
killall "compton"
compton -c -o 0.3 -r 8 -f --inactive-dim 0.2 & 
xsetroot -cursor_name left_ptr &
#killall polybar
#polybar -c ~/.config/polybar/config bspwm bottom
~/.config/polybar/polybar_launcher 

#Scratchpad
#github.com/davidv171/freshDots
#kitty --class=scratchpad sh ~/.config/bspwm/scripts/scratch &
#bspc rule -a scratchpad state=floating desktop=^2 follow=false
#kitty --class=hhtop -e htop
#bspc rule -a scratchpad sticky=on state=floating hidden=on

#bspc desktop 2-shell --focus &



